TRIFFHIR-527: Created a new tab in Publish tab of main menu to show c…
lantanagroup/trifolia-on-fhir pull request #59
Opened 2021-04-23 18:47 UTC by ajagann1

…urrent custom publishing settings (read only).  Can only edit these settings within the Edit IG page.

2021-04-23 23:38 UTC, seanmcilvenna requested changes
Two main things:
1. This is _too_ restrictive, now. The user still needs to be able to edit the template settings for publishing when the IG does not have these settings pre-determined.
2. The changes discussed earlier should not affect the use of "custom-menu" or "ignore-warnings". It is _only_ related to the publish template settings.

2021-04-23 23:38 UTC, seanmcilvenna commented on apps/client/src/app/publish/publish.component.html
> +      <trifolia-fhir-custom-publish-settings [readOnly]="true" [selectedImplementationGuide]="selectedImplementationGuide"
`[readOnly]="true"` is too definitive here. We don't want it to _always_ be read-only... It should be read-only when the user has specified the publishing template settings in the Edit IG. It is not _required_ to specify the publish settings in Edit IG... If the IG _doesn't_ specify the publish settings, then the user should be able to determine what template should be used as part of the publishing process.

2021-04-23 23:38 UTC, seanmcilvenna commented on apps/client/src/app/publish/publish.component.ts
> +import {ImplementationGuide} from '../../../../../libs/tof-lib/src/lib/r4/fhir';
Can `IImplementationGuide` from `fhirInterfaces.ts` be used here instead of a version-specific instance of ImplementationGuide?

2021-04-23 23:38 UTC, seanmcilvenna commented on apps/client/src/app/implementation-guide-wrapper/custom-menu/custom-menu.component.html
> +      <button type="button" class="btn btn-primary" title="Generate the XML menu" (click)="generate()" [disabled]="readOnly">
The changes discussed earlier are _only_ for the purposes of the the publish template settings... Doesn't have anything to do with the `custom-menu` component or the `ignore-warnings` component. I think these changes to these two components can be reverted.

2021-04-23 23:38 UTC, seanmcilvenna commented on apps/client/src/app/implementation-guide-wrapper/ignore-warnings/ignore-warnings.component.html
> +    <textarea class="form-control" rows="4" [(ngModel)]="intervalValue" [ngModelOptions]="{ updateOn: 'change' }" [disabled]="readOnly"></textarea>
The changes discussed earlier are _only_ for the purposes of the the publish template settings... Doesn't have anything to do with the `custom-menu` component or the `ignore-warnings` component. I think these changes to these two components can be reverted.

2021-04-29 22:34 UTC, ajagann1 commented
Hey Sean,

I dialed all these changes back because, like I said in the call, I did way more than you suggested that I do for this ticket.  I've reverted this commit and I'll have a new commit for you to look at shortly.

Thanks!

2021-04-29 22:34 UTC, closed without merging